accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="loginview"),
    path('register/', views.register_view, name="registerview"),
    path('logout/', LogoutView.as_view(), name="logoutview"),
]

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [    
    path('', views.home_view, name='homeview'),
]

virtualhub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse


def register_view(request):
    return HttpResponse("Essa é a tela de Register")

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def home_view(request):
    return render(request, 'core/home.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Página de Acesso</h2>
    <form method="post" action="{% url 'accounts:loginview' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Entrar</button>
    </form>
</body>
</html>

core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>Dashboard</h1>
    <p>Essa é a Dashboard</p>
    <form action="{% url 'accounts:logoutview' %}" method="post">
        {% csrf_token %}
        <button type="submit">Sair</button>
    </form>
</body>
</html>